# Generated by Django 5.1.1 on 2024-09-06 18:22

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Является ли администратор главным?')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания аккаунта')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания аккаунта')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания аккаунта')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почтовый адрес')),
                ('type', models.CharField(max_length=30, verbose_name='Тип пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
