# Generated by Django 5.1.1 on 2024-09-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='last_login',
        ),
    ]
