# Generated by Django 5.1.1 on 2024-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name': 'Почтовый адрес',
                'verbose_name_plural': 'Почтовые адреса',
            },
        ),
    ]
