# Generated by Django 5.1.1 on 2024-09-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара, который был добавлен в корзину')),
                ('buyer_id', models.IntegerField(verbose_name='ID покупателя, у которого данный товар находится в корзине')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, которое было добавлено в корзину')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
