# Generated by Django 5.1.1 on 2024-09-06 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара, который был добавлен в корзину')),
                ('buyer_id', models.IntegerField(verbose_name='ID покупателя, у которого данный товар находится в корзине')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, которое было добавлено в корзину')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField(verbose_name='ID продавца')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество на складе')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('number_of_purchases', models.IntegerField(default=0, verbose_name='Количество проданных товаров')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время добавления товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товара, на который оставили отзыв')),
                ('buyer_id', models.IntegerField(verbose_name='ID покупателя, оставившего отзыв')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата и время, когда был оставлен отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
