# Generated by Django 5.1.1 on 2024-09-15 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 0, 19, 45, 612118), verbose_name='Дата и время, когда был оставлен отзыв'),
        ),
    ]
